### PR TITLE
feat: session end analytics: tools, llms, duration

### PR DESCRIPTION
**Pull request by heethjain21**
## 📥 Pull Request

**📘 Description**
- Counting the no of events based on event type
- Logging the no of events on session end
- Also logging the session duration

**🔄 Related Issue (if applicable)**
[Add duration + LLM analytics at end of session in CLI #380
](https://github.com/AgentOps-AI/agentops/issues/380)

**🎯 Goal**
- Have some additional metrics shown on session ending

**🔍 Additional Context**
- I checked if there was an API for GET session by Id, but couldn't find it, so the next best solution was to just simply calculate the events

**🧪 Testing**
- Not needed, since its just logging

### CODE REVIEW

**Comment by HowieG** [comment]
Hey @heethjain21 - we're able to calcuate these API-side and for duration we do have that in our dashboard as one of our key features - https://app.agentops.ai/
So we don't have a need for this PR unfortunately

**Comment by HowieG** [comment]
I guess the intention was to log them at the end just like we log the cost. Again not sure if there's a need and I think we have to keep the terminal more or less clean because developers that use our sdk may not want a lot of noise especially considering we're an add-on for observability not like a primary tool for accomplishing a task

**Comment by HowieG** [comment]
Actually I think duration is valuable! Asking team about counts

**Review by HowieG — APPROVED** [review]

**Comment by heethjain21** [comment]
Hi @HowieG , 

This PR's workflow didn't run all the tests (earlier), so couldn't realize `dateutil` package messed up.
I had it installed the package locally, so couldn't replicate it for the tests locally (and hence couldn't catch the tests failure)

I have corrected the issue in this Pull Request: https://github.com/AgentOps-AI/agentops/pull/387
Please take a look, and merge it so the PR workflows get fixed.

**Comment by areibman** [comment]
Thanks @heethjain21 !

**Comment by HowieG** [comment]
Hey @heethjain21 thanks for followup my bad I also merged without checking the workflows. I ended up replacing the dateutil logic with the builtin datetime to minimize addition of new dependencies

**Comment by heethjain21** [comment]
Alright, thanks!

**Pull request merged**
