### PR TITLE
feat: disable AgentOps flag

### PR DESCRIPTION
**Pull request by heethjain21**
## 📥 Pull Request

**📘 Description**
- Added `is_disabled` flag during `init()` which is further passed to the Client config
- Added global `enable()` and `disable()` functions to perform the same
- When `is_disabled` is set to True, all sessions, event recording are disabled
- Updated docs for the same

**🔄 Related Issue (if applicable)**
[Create a way to disable AgentOps functions entirely #349
](https://github.com/AgentOps-AI/agentops/issues/349)

**🎯 Goal**
- Add a global way to disable AgentOps completely with a flag

**🔍 Additional Context**
- None

**🧪 Testing**
- Added test cases for `sessions`, `canary` (wasn't sure if it was needed here), `record_actions`, `record_tools`

### CODE REVIEW

**Comment by heethjain21** [comment]
Add reviewers option is not available for me, so tagging instead: @areibman @HowieG 

Side Notes:
- All old and new tests pass (using `pytest`)
- Test Notebooks seems to be failing for other PRs too (and I haven't made any changes in that part)

**Comment by HowieG** [comment]
Hey @heethjain21 thanks I think the team took a look and didn't feel we needed this @areibman @siyangqiu lmk

**Comment by siyangqiu** [comment]
Yes. I agree with Howard. Thanks for putting in this work though

**Comment by heethjain21** [comment]
Ahh nvm.

Could you also please also close the issues (like these), so it doesn't create confusion again in the future?

Edit 1: Closing the PR

Edit 2: Checked the Issue has been closed

**Pull request closed without merging**
