### PR TITLE
[HotFix] Fix linting and formatting for the CI tests to pass 100%

### PR DESCRIPTION
**Pull request by dot-agi**
## 📥 Pull Request

**📘 Description**
* Linting and formatting the files using the `ruff` tool so that the CI tests pass
* Add rules in the pre-commit hook to ensure only required rules are checked

**🧪 Testing**
TODO

### CODE REVIEW

**Comment by teocns** [comment]
What's the backstory behind this PR's initiative? Let's get add more details specifically addressing

- Why is it using `black` if #510 states `ruff` is enough
- What does the hotfix address (specific issues / PRs being blocked?)

**Comment by dot-agi** [comment]
> What's the backstory behind this PR's initiative? Let's get add more details specifically addressing
> 
> * Why is it using `black` if [ci: pre-commit hooks for static analysis #510](https://github.com/AgentOps-AI/agentops/pull/510) states `ruff` is enough
> * What does the hotfix address (specific issues / PRs being blocked?)

* Not using `black`, only `ruff`
* CI test fails for linting so it fixes that

**Comment by teocns** [comment]
🤔 I only see general CI failures for codecov, can you help me locate the failures?

**Comment by dot-agi** [comment]
[Here's](https://github.com/AgentOps-AI/agentops/pull/522/commits/cf79e1c279fc1a843710daea1e1c9febff97ab03) the commit from #522 where a lot of unrelated files weren't linted. 

I opened this PR to fix linting for these files so that it's on `main` and update the rules in `pyproject.toml`, if required after discussion.

**Comment by teocns** [comment]
https://github.com/AgentOps-AI/agentops/blob/517c93ed14e6f90c0ee791fbe7252d909b1d4afd/pyproject.toml#L72-L106

**Comment by dot-agi** [comment]
~~Barring those the main codebase was not linted.~~

Ah okay. Closing this.

**Pull request closed without merging**
