### PR TITLE
Github stars dynamically updates

### PR DESCRIPTION
**Pull request by albertkimjunior**
## 📥 Pull Request

**📘 Description**
I'm the goat

**🔄 Related Issue (if applicable)**
#267 is related, but that'll be separate PR

**🎯 Goal**
Dynamic data in MDX-formatted docs

**🔍 Additional Context**
Any extra information or context to help us understand the change?

**🧪 Testing**
Use mintlify dev and see for yourself nerds

Thank you for your contribution to Agentops!

### CODE REVIEW

**Comment by albertkimjunior** [comment]
@bboynton97 @areibman I feel like it makes more sense to list the exact number nth star the user will be rather than rounding up to nearest 1,000th, thoughts?

**Comment by braelyn-ai** [comment]
i like the idea of rounding up to at least the next hundred. github only shows to the nearest hundred, so it adds an element of curiosity as to whether or not they flip the number

**Review by braelyn-ai — APPROVED** [review]
its not as elegant as a reusable component, but if this doesnt cost us $400/mo, im down

**Comment by albertkimjunior** [comment]
lol yeah it's so scuffed, but it also costs $0 a month haha

**Comment by albertkimjunior** [comment]
I'm gonna hold off on merging this and do one more quick experiment to see if there is a slightly more elegant way to do this and also do the 100s round up later

**Comment by albertkimjunior** [comment]
That won't be till next Monday tho

**Comment by areibman** [comment]
> That won't be till next Monday tho

Thanks dawg

**Review by braelyn-ai — APPROVED** [review]

**Pull request merged**
