### PR TITLE
[FEAT] TaskWeaver Integration

### LINKED ISSUE #500: [Feature]: TaskWeaver Support
### 💡 Feature Description and Proposed Solution

https://github.com/microsoft/taskweaver/

Add support for TaskWeaver, similar to AutoGen.

### 🤔 Related Problem

_No response_

### 🤝 Contribution

- [ ] Yes, I'd be happy to submit a pull request with these changes.
- [ ] I need some guidance on how to contribute.
- [ ] I'd prefer the AgentOps team to handle this update.

### PR DESCRIPTION
**Pull request by dot-agi**
## 📥 Pull Request

**📘 Description**
* Closes #500 
* Adds support for [TaskWeaver](https://github.com/microsoft/taskweaver/) by using the `SessionEventHandler` class
* Adds support for tracking the `User`, `Planner`, and `CodeInterpreter` agents present in TaskWeaver

**🧪 Testing**
Tested using the below code by checking the events in the dashboard -

```python
import agentops
from dotenv import load_dotenv
import os

from taskweaver.app.app import TaskWeaverApp
from agentops.partners.taskweaver_event_handler import TaskWeaverEventHandler

load_dotenv()
AGENTOPS_API_KEY = os.getenv("AGENTOPS_API_KEY")

agentops.init(api_key=AGENTOPS_API_KEY, default_tags=["taskweaver", "test"])

# Assuming the current project directory contains the taskweaver_config.json file
app_dir = "./project/"
app = TaskWeaverApp(app_dir=app_dir)
session = app.get_session()
handler = TaskWeaverEventHandler()

session.event_emitter.register(handler)

user_query = "hello, what can you do?"
# response_round = session.send_message(user_query, event_handler=handler)
response_round = session.send_message(user_query)
print(response_round.to_dict())
```

**⚠️ Caveats**
* Every information that we need to track is not present out of the box in the `SessionEventHandler` class. This is a TaskWeaver architecture-related problem that we need to resolve.
* We assume for brevity that the default agent is `Planner` since it is the intermediary between the `User` and the `CodeInterpreter`. This is not a scalable solution and can be the root cause of problems in the future.
* Extensive testing is required with different and preferably complex codes using TaskWeaver in [library](https://microsoft.github.io/TaskWeaver/docs/usage/library/) mode.

**🗒️ To Do**
* Resolve above mentioned caveats.
* Create docs page linking to the example.
* Update the README to include a link to the docs page.

### CODE REVIEW

**Comment by teocns** [comment]
> Every information that we need to track is not present out of the box in the SessionEventHandler class. This is a TaskWeaver architecture-related problem that we need to resolve.

Can you share further findings i.e the data set / schema yielded by TaskWeaver's?

**Comment by areibman** [comment]
Also todo:
- Create docs page linking to the example
- Update the README to include a link to the docs page

**Comment by dot-agi** [comment]
Currently I am working on tracking the LLM information for the `LLMEvent` object.

For this I need to have the `chat_completion` and `chat_completion_stream` methods in `LLMApi` class exposed within the `TaskWeaver` class object. I am working on a quick hack for this.

**Comment by teocns** [comment]
> For this I need to have the chat_completion and chat_completion_stream methods in LLMApi class exposed within the TaskWeaver class object. I am working on a quick hack for this.

hey could you share backlinks and reference to the code to make it easy to jump in? I want to have a second hand pair of eyes on this to make this move faster

**Comment by dot-agi** [comment]
> > For this I need to have the chat_completion and chat_completion_stream methods in LLMApi class exposed within the TaskWeaver class object. I am working on a quick hack for this.
> 
> hey could you share backlinks and reference to the code to make it easy to jump in? I want to have a second hand pair of eyes on this to make this move faster

TaskWeaver runs as a CLI application in isolation mode by default but you can use it as a [library](https://microsoft.github.io/TaskWeaver/docs/usage/library) too. TaskWeaver extensively uses the [Injector](https://injector.readthedocs.io/en/latest/index.html) library (API reference [here](https://injector.readthedocs.io/en/latest/api.html#injector.Injector)]) in their codebase to inject the dependencies.

This is the examples code from the docs that we are also using to test the integration -

```python
from taskweaver.app.app import TaskWeaverApp

# This is the folder that contains the taskweaver_config.json file and not the repo root. Defaults to "./project/"
app_dir = "./project/"
app = TaskWeaverApp(app_dir=app_dir)
session = app.get_session()

user_query = "hello, what can you do?"
response_round = session.send_message(user_query)
print(response_round.to_dict())
```

The `app_dir` is the [project directory](https://microsoft.github.io/TaskWeaver/docs/quickstart#project-directory) which will contain all the code and logs generated by TaskWeaver. All the configurations are defined in a file called `task weaver_config.json` which will contain the configurations for different items based on the classes defined in [`taskweaver/llm/base.py`](https://github.com/microsoft/TaskWeaver/blob/main/taskweaver/llm/base.py)

The [`TaskWeaverApp`](https://github.com/microsoft/TaskWeaver/blob/main/taskweaver/app/app.py) class contains the `app_injector` attribute which is the Injector object to bind and get the dependencies. In our case, we have the [`LlmApi`](https://github.com/microsoft/TaskWeaver/blob/main/taskweaver/llm/__init__.py) class which is injected into the `TaskWeaverApp` object and is used by `Planner` and `CodeGenerator` classes.

In `LlmApi` you are setting up the [`CompletionService`](https://github.com/microsoft/TaskWeaver/blob/main/taskweaver/llm/base.py#L79) for the different LLM providers (OpenAI, Anthropic, Qwen etc.) and injecting them using the `injector` object. Based on the configurations from `task weaver_config.json`, the `chat_completion` of the configured LLM(s) is injected via the `_set_completion_service` method and their `chat_completion` method is set to the [`chat_completion`](https://github.com/microsoft/TaskWeaver/blob/main/taskweaver/llm/__init__.py#L135) method of the `LlmApi` class.

This method is now used to chat with the LLM and output the responses. This is what we need to monkey patch. We do not have a direct access to the `LlmApi` instance in the `TaskWeaverApp` object but we are exposed to the `app_injector` object which is of type `Injector`. Using this we can use the code below to fetch the configured `LlmApi` class -

```python
from taskweaver.llm import LLMApi
llmapi = app.app_injector.get(LLMApi)
```

Now we have the `chat_completion` method exposed for us which can be monkey patched. To bind it back we can use the `app_injector` object again. For example, if we were to substitute [`OpenAIService`](https://github.com/microsoft/TaskWeaver/blob/main/taskweaver/llm/openai.py_) with [`AnthropicService`](https://github.com/microsoft/TaskWeaver/blob/main/taskweaver/llm/anthropic.py) we would use the following code -

```python
from taskweaver.llm.anthropic import AnthropicService

llmapi.completion_service = llmapi.injector.get(AnthropicService)
llmapi.injector.binder.bind(AnthropicService, to=llmapi.completion_service)

app.app_injector.binder.bind(LLMApi, to=llmapi)
```

Also - to override the `chat_completion` function directly, we can use the following code -

```python
from taskweaver.llm.anthropic import AnthropicService

llmapi.chat_completion = AnthropicService.chat_completion
app.app_injector.binder.bind(LLMApi, to=llmapi)
```

**Comment by the-praxs** [comment]
Here's the graph of the classes in TaskWeaver:

graphviz

**Comment by areibman** [comment]
Awesome!!! Almost at the finish line. Can we do 2 things:
1. When the AgentOps session is created, can you please insert `"TaskWeaver"` as one of the tags? 
2. Can you add a short documentation page for how to run it?

**Review by areibman — APPROVED** [review]
Very nice-- elegant!

**Pull request merged**
