### PR TITLE
doc: swarmzero integration

### PR DESCRIPTION
**Pull request by ToJen**
## 📥 Pull Request

**📘 Description**
AgentOps integration guide for SwarmZero

**🧪 Testing**
Ran the SwarmZero agent and verified that the logs were generated and also published to the AgentOps dashboard.

### CODE REVIEW

**Comment by areibman** [comment]
Awesome, @ToJen! Looks good to me so far, let me know when it's ready to merge

**Comment by ToJen** [comment]
Thanks @areibman, I think the github actions workflow needs an approver to run but other than that, it's ready to merge.

**Comment by ToJen** [comment]
@areibman is there anything you'd like me to add

**Review by areibman — APPROVED** [review]
Awesome!!

**Comment by areibman** [comment]
Thanks @ToJen! Will promote on our our end

**Comment by ToJen** [comment]
Thanks @areibman, let me know if you need any more info to promote it

**Pull request merged**
