### PR TITLE
[FEATURE] Add support for Mistral via the `mistral` Python SDK

### PR DESCRIPTION
**Pull request by dot-agi**
## 📥 Pull Request

**📘 Description**
Adds support for the Mistral models tracking for `mistral >= 1.0.1` Python SDK with examples

**🎯 Goal**
To extend the functionality of Agentops

**🧪 Testing**
Tested the functions with the provided tests file

### CODE REVIEW

**Comment by dot-agi** [comment]
@bboynton97 @HowieG @siyangqiu @areibman this is ready for review!

**Comment by dot-agi** [comment]
Cleaned and fixed up some items while creating the #382 PR.

This can also be reviewed.

**Comment by dot-agi** [comment]
@bboynton97 @areibman can you guys review this?

**Review by areibman — APPROVED** [review]
Works great. Pushed some changes so prices track correctly. Nicely done @the-praxs !

**Pull request merged**
