### PR TITLE
Updating retrieval for multion sdk changes

### PR DESCRIPTION
**Pull request by HowieG**
MultiOn updated the location of their retrieval function in their sdk so updating our corresponding example

### CODE REVIEW

**Comment by braelyn-ai** [comment]
just a notebook change?

**Comment by HowieG** [comment]
> just a notebook change?

yes

**Comment by braelyn-ai** [comment]
why

**Comment by braelyn-ai** [comment]
pls clear outputs, there's a ton of unnecessary text rn

**Comment by HowieG** [comment]
> why

The description explains why

**Comment by HowieG** [comment]
> pls clear outputs, there's a ton of unnecessary text rn

Done. I had cleared outputs but VSCode's been finicky

**Review by braelyn-ai — APPROVED** [review]

**Pull request merged**
