### PR TITLE
bugfix: 291 - llm_tracker is not an attribute in client class

### PR DESCRIPTION
**Pull request by andkoma**
📘 Description
initialize the llm_tracker in class client with None

🔄 Related Issue (if applicable)
https://github.com/AgentOps-AI/agentops/issues/291

🎯 Goal
fix the bug, that the client class has in some cases no attribute for llm_tracker.

🔍 Additional Context
Looks like the class init is not complete processed and the attribute did not been created in some circumstances?

🧪 Testing
Fix in local environment, re-run the crewai application with agentops in two modes.
a) enabled
b) disabled.

### CODE REVIEW

**Comment by areibman** [comment]
Thanks for this! @bboynton97 what do you think?

**Comment by braelyn-ai** [comment]
Thank you for the contribution @andkoma! I think there's an underlying issue here we need to investigate, but this does prevent the case for an exception halting the execution of an agent due to AgentOps.

@areibman I say we merge this and investigate the issue after

**Comment by braelyn-ai** [comment]
@andkoma Could you merge upstream and run `black .` 

If you dont have Black installed, run:
```
pip install black 'black[jupyter]'
```

**Comment by andkoma** [comment]
Ok. 
My change was just the insert of a single line statement.
This could not be the root cause for the merge result.

Regards

**Comment by braelyn-ai** [comment]
There's no merge conflict. Your branch is behind and not formatted properly

**Review by braelyn-ai — APPROVED** [review]

**Comment by andkoma** [comment]
I just checked this behavior,
I’ve made the change inside the web interface of the forked repo.
Maybe in this case the embedded editor destroys your expected formatting.

I will drop the fork and create a fresh one.

Regards and sorry for any circumstances
Andrew

**Pull request merged**
