### PR TITLE
Add Ollama API integration with AgentOps

### PR DESCRIPTION
**Pull request by sarath59**
### Overview
This pull request integrates the Ollama API with AgentOps, enabling tracking of both synchronous and asynchronous interactions. The following changes were made:

### Changes Made
- **llm_tracker.py**:
  - Added support for Ollama API.
  - Implemented methods to handle synchronous and asynchronous responses.
  - Patched Ollama chat methods for tracking.

- **client.py**:
  - Initialized and utilized the updated `LlmTracker`.
  - Ensured `override_api` method in `LlmTracker` is called during client initialization.

### Test Script
Created a test script to verify the integration. The script performs synchronous and asynchronous calls to the Ollama API and logs the interactions.

**Test Script**:
```python
import ollama
from agentops import Client
import asyncio

# Initialize the AgentOps client with your API key
client = Client(api_key="YOUR_API_KEY_HERE")

# Start a session
session_id = client.start_session(tags=["ollama_test"])

try:
    # Synchronous chat call to Ollama API
    sync_response = ollama.chat(
        model='orca-mini',
        messages=[{'role': 'user', 'content': 'Why is the sky blue?'}]
    )
    print("Sync Response:", sync_response)

    # Asynchronous chat call to Ollama API using asyncio.to_thread to run the sync method
    async def async_chat():
        response = await asyncio.to_thread(ollama.chat,
                                           model="orca-mini",
                                           messages=[{"role": "user", "content": "Why is the sky blue?"}])
        return response

    async def main():
        async_response = await async_chat()
        print("Async Response:", async_response)

    asyncio.run(main())

    # End the session successfully
    client.end_session("Success")

except Exception as e:
    # End the session with failure if there is an exception
    client.end_session("Fail", str(e))
    raise
Results
The script successfully logged interactions with the Ollama API and provided session replay links for review. Both synchronous and asynchronous interactions were tracked and logged correctly.

Conclusion
This integration enables comprehensive monitoring and analysis of interactions with Ollama, facilitating better understanding and debugging of API usage within the AgentOps framework.

### CODE REVIEW

**Comment by braelyn-ai** [comment]
#237 also exists for ollama support

**Comment by sarath59** [comment]
> #237 also exists for ollama support

I thought I could give it a try. Let me know how can I proceed. Thanks.

**Comment by areibman** [comment]
> > #237 also exists for ollama support
> 
> I thought I could give it a try. Let me know how can I proceed. Thanks.

Thanks @sarath59 for helping. Perhaps we can combine the changes in this PR with #237? Namely, you've provided the unit tests for this, whereas that branch has not.

**Comment by sarath59** [comment]
> > > #237 also exists for ollama support
> > 
> > 
> > I thought I could give it a try. Let me know how can I proceed. Thanks.
> 
> Thanks @sarath59 for helping. Perhaps we can combine the changes in this PR with #237? Namely, you've provided the unit tests for this, whereas that branch has not.

Sure @areibman , I am good with that if that helps. Let me know if I could help with anything else. Thanks.

**Comment by braelyn-ai** [comment]
closed in favor of #237

**Pull request closed without merging**
