### PR TITLE
fix: litellm conflict with openai on lib override

### LINKED ISSUE #471: [Bug]: LiteLLM conflicts with OpenAI
### Contact Details

_No response_

### 📦 Package Version

0.3.14

### 🎞️ Framework Version

openai==1.52.2, litellm==1.50.2

### 🔎 Describe the Bug

LiteLLM alone: Works
image

OpenAI alone: Works
image

Import both OpenAI and LiteLLM - Doesn't Work
image

Same does not apply when you only use LiteLLM
image

### 🤝 Contribution

- [ ] Yes, I'd be happy to submit a pull request with these changes.
- [ ] I need some guidance on how to contribute.
- [ ] I'd prefer the AgentOps team to handle this update.

### PR DESCRIPTION
**Pull request by teocns**
Fixes #471 

- Removed `original_oai_create` and `original_oai_create_async` variables since we no longer override OpenAI's methods
- Modified `override()` and `undo_override()` to only handle LiteLLM's methods 
- Updated `_override_completion()` and `_override_async_completion()` to only store and patch LiteLLM's methods

This way, when both providers are used:
- OpenAIProvider will handle overriding OpenAI's completion methods 
- LiteLLMProvider will only handle overriding LiteLLM's completion methods 
- No more conflicts between the two providers ✅ 

### A bit more of explanation

LiteLLM's completion method is completely separate from OpenAI's `Completions.create`
Even though LiteLLM uses OpenAI's format internally, it has its own implementation
When we call `litellm.completion()`, it doesn't actually call OpenAI's `Completions.create`

##### Breakdown 

- `test_provider_override_independence()`:
  1. Verifies that each provider only overrides its own methods
  2. Checks that the original methods are properly stored and restored
  3. Ensures no cross-contamination between providers
- `test_provider_override_order_independence()`:
  1. Verifies that the order of provider initialization doesn't matter
  2. Tests both possible orders (OpenAI first vs LiteLLM first)
  3. Ensures each provider's overrides remain intact regardless of order
  
##### What's being verified
- Each provider only overrides its intended methods
- Original methods are properly stored and can be restored
- The order of provider initialization doesn't affect the overrides
- No provider interferes with another provider's overrides

```
python tests/test_providers.py
```

### CODE REVIEW

**Comment by areibman** [comment]
I ran this in `python` and it didn't work for OpenAI

```
import litellm
import openai
import agentops

agentops.init(default_tags=["litellm"])

message = [{"role": "user", "content": "Write a 12 word poem about secret agents."}]

litellm.completion(model="claude-3-sonnet-20240229", messages=message, temperature=0)

client = openai.OpenAI()

client.chat.completions.create(model="gpt-4o", messages=message, temperature=0)```

**Comment by areibman** [comment]
@the-praxs Can you give it a look?

**Comment by dot-agi** [comment]
> @the-praxs Can you give it a look?

Testing it - same issue as yesterday - only the first `create` uses the patched function.

I am trying to troubleshoot the root cause.

**Comment by teocns** [comment]
closing in favor of #476

**Comment by areibman** [comment]
If we want to avoid client conflicts, perhaps we can instead use their official observability documentation https://docs.litellm.ai/docs/observability/arize_integration

**Comment by teocns** [comment]
Since the other PR was closed by the author will consider this as "Resolves #471 "

**Pull request closed without merging**
