### PR TITLE
ci: pre-commit hooks for static analysis

### LINKED ISSUE #509: Integrate `black` and `ruff` with pre-commit hooks in the CI
### 💡 Feature Description and Proposed Solution

`black` and `ruff` are for linting the code to adhere to PEP-8 format and type checks.

Using pre-commit hooks will allow us more flexibility in the rules that it should respect when linting our codebase.

### 🤔 Related Problem

_No response_

### 🤝 Contribution

- [ ] Yes, I'd be happy to submit a pull request with these changes.
- [ ] I need some guidance on how to contribute.
- [ ] I'd prefer the AgentOps team to handle this update.

### PR DESCRIPTION
**Pull request by teocns**
Fixes #509 

#### DISCLAIMER
Ruff's formatter is actually compatible with Black's style, so we get the best of both worlds.
We can't have both or they will fight over each-other. Matter of fact, state-of-the-art repositories only go with ruff.

## Usage

Install once
```
(agentops) ➜  agentops git:(githooks) pre-commit install        
pre-commit installed at .git/hooks/pre-commit
```

Run manually (will run automatically on commit)
```
(agentops) ➜  agentops git:(githooks) pre-commit run --all-files
[INFO] Initializing environment for https://github.com/psf/black.
[INFO] Installing environment for https://github.com/psf/black.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
```

## Todo

- [x] Update the contributor's guideline
- [x] Run hook on repository to _fix_ all preexisting issues
- [x] Update `pyproject.toml` to conform with current rules and define new standards; we can decide to ignore rules that won't pass checks for now, and fix those issues on the run or Q5

### CODE REVIEW

**Comment by teocns** [comment]
Ready  for merge @areibman @the-praxs 

image

**Comment by teocns** [comment]
for the sake of clarity and linear history this PR should not be squashed but git-merged with fast forward, so that the commit showing up on history (git blame) will be [run ruff on pre-existing issues](https://github.com/AgentOps-AI/agentops/pull/510/commits/c1ea612f302267846ba374ed8f23d75d21cca58a)


image

**Review by dot-agi — COMMENTED** [review]
A-ok

**Comment by dot-agi** [comment]
Think we need to add pre-commit hooks in the repo and add relevant dependencies in the `pyproject.toml` file under a `dev` section.

**Comment by teocns** [comment]
> @the-praxs  Think we need to add pre-commit hooks in the repo and add relevant dependencies in the pyproject.toml file under a dev section.

tru, don'

**Review by areibman — APPROVED** [review]
I <3 clean code. Good stuff

**Pull request merged**
